### PR TITLE
Configure CMake

### PR DESCRIPTION
**Pull request by Leo2807**
Copied most of the CMake config from
https://github.com/hughperkins/coriander-dnn/blob/master/CMakeLists.txt
to keep the build system similar to the other coriander build systems.
KISS & don't reinvent the wheel.

### CODE REVIEW

**Comment by iame6162013** [comment]
I do have a couple of remarks:
Should we have a ".editorconfig" in our git repo?

"cusolver.h" isn't a header that is present in the cuSolver library umbrella.
Since we want to primarily implement the cuSolverDN part, I added the cusolverDn.h header.
But because it's unidiomatic, look at the coriander source code or an already implemented plugin, we ought to define it in: "include/coriander-solver/cocl_solver_dn.h"

Thirdly, you didn't specify in which header "add2", in cocl_solver.cpp, was declared in.

Lastly, I think it's better if we don't add a test function, "add2", and instead implement the (~)constructor.

**Comment by Leo2807** [comment]
1. Yes, uniform code is nicer to look at
2. `cusolver` was more of a guess
3. It is declared in `cusolver.h`
4. I need something to test the build system, kay?

I'll rework my includes and remove add2

**Comment by iame6162013** [comment]
1.  ok
2.  Could you create a patch?
3.  But you didn't include `cusolver.h` in the .cpp file. Could you include `cocl_solver_dn.h`, to comply with the previous remark?
4.  No problem, so the build system does work? Lovely. :)

**Comment by Leo2807** [comment]
Done, I also split up my commits

**Pull request merged**
